In [24]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
import numpy as np

In [26]:
np.array([1.0, 2.0, 3.0]) * np.array([1.0, 2.0, 3.0])

array([ 1.,  4.,  9.])

In [27]:
np.array([1.0, 2.0, 3.0, 4.0]).reshape(2, 2)

array([[ 1.,  2.],
       [ 3.,  4.]])

In [28]:
y = np.array([(1, 2.0, 'Hello'), (2, 3.0, 'World')],
     dtype=[('foo', '>i4'), ('bar', '>f4'), ('baz', '|S10')])

In [29]:
y['foo'].dtype

dtype('>i4')

## Task 1

In [71]:
X = np.random.normal(loc = 1, scale = 10, size = (1000, 50))
X

array([[  2.86698572,   6.16332467, -17.2296932 , ...,  -2.10810257,
         10.0117795 ,   5.41768219],
       [ -9.30019029, -12.15779564,  -6.7308473 , ...,  15.69298093,
         -3.79741527,  10.40175041],
       [ 10.34470808,   2.59941276,   6.39365258, ...,  -9.6399362 ,
        -11.63095292, -12.2699102 ],
       ..., 
       [ 18.6076343 ,   9.89792173,  -4.13898181, ..., -12.9671304 ,
          3.8415555 ,   9.85177528],
       [ 10.15382536,  -9.85992916,   3.76331105, ...,   4.53919921,
         -1.98359583,  -3.28820261],
       [ -3.2751666 ,  -0.24858777, -19.0114366 , ...,   7.24406799,
          8.26556603,  14.805481  ]])

In [85]:
X_col_means = mean(X, axis = 0)
X_col_dev = std(X, axis = 0)
X_norm = ((X - X_col_means)  / X_col_dev)
X_norm

array([[ 0.13750257,  0.49404236, -1.86200964, ..., -0.38377187,
         0.92269005,  0.47409543],
       [-1.07514166, -1.35403107, -0.81906209, ...,  1.42857031,
        -0.46562798,  0.96820439],
       [ 0.88277138,  0.13454628,  0.48471598, ..., -1.15059372,
        -1.25317872, -1.27941143],
       ..., 
       [ 1.70629771,  0.87075566, -0.56158809, ..., -1.48933795,
         0.30236183,  0.91368114],
       [ 0.86374702, -1.12224252,  0.22341981, ...,  0.29299511,
        -0.28327425, -0.38898578],
       [-0.47465637, -0.15273496, -2.0390067 , ...,  0.5683799 ,
         0.74713314,  1.40478003]])

## Task 2

In [3]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [11]:
row_sums = np.sum(Z, axis = 1)
np.nonzero(row_sums > 10)

(array([1, 4, 5]),)

## Task 3

In [15]:
np.vstack((np.eye(3), np.eye(3)))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])